FROM ubuntu:latest

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    binutils-arm-linux-gnueabihf \
    gcc-arm-linux-gnueabihf \
    g++-arm-linux-gnueabihf \
    make \
    bsdmainutils \
    python3 \
    python3-pip \
    python3-tk \
    && rm -rf /var/lib/apt/lists/*

# Installer PySimpleGUI avec pip
RUN pip3 install --no-cache-dir --break-system-packages PySimpleGUI

# Définir le compilateur par défaut (optionnel)
ENV AS=arm-linux-gnueabihf-as
ENV CC=arm-linux-gnueabihf-gcc
ENV PYTHONUNBUFFERED=1

# Définir le point d'entrée
CMD ["/bin/bash"]

